Package update and python version update to 3.7 - 3.9 (#181)
* Pyproj update

Change the way of CRS transformation method
Reduced the calling of proj2equidistant to prevent performance loss

* Updated geopandas

* Updated pyproj and fixed deprecation warning for escape sequence

* Fixed test_aggregate_components with pandas 1.2.4

* Fixed test_mv_to_pypsa with pandas 1.2.4

* Fixed test_integrate_component with pandas 1.2.4

* Fixed test_add_generators_timeseries with pandas 1.2.4
Fixed test_add_storage_unit_timeseries with pandas 1.2.4

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

* Fixed test_add_line with pandas 1.2.4

Expected value deviated a bit, don't know why.

* Fixed test_append_lv_components with pandas 1.2.4

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported.

* Fixed test_set_seed 1.2.4

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported.

* Fixed test_transformer_buses with Pandas 1.2.4

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported.

* Fixed test_target_capacity with Pandas 1.2.4

Use numpy.isclose()

>       assert (gens_before[gens_before["type"] == "solar"].p_nom.sum() ==
                edisgo.topology.generators_df[
                    edisgo.topology.generators_df["type"] == "solar"].p_nom.sum())
E       assert 10.203790999999992 == 10.203790999999994

io/test_generators_import.py:458: AssertionError

* Fixed test_oedb_with_worst_case_timeseries with Pandas 1.2.4

Added .tolist() in numpy.isclose(...)

E       TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

* Update requirements based on ding0 pull request #340

* Added python version requirements at least py37

* Update installation documentation

Co-authored-by: birgits <birgit.schachler@rl-institut.de>